site_name: MkDocs PIV Bootstrap
site_url: https://example.com

theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Light mode

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      guess_lang: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

extra_css:
  - stylesheets/extra.css
  - stylesheets/blog-index.css
